### ISSUE TITLE
Network bandwidth much higher than it should be

### ISSUE THREAD

**Issue by zacwitte** [WPI-ARC/datalink_toolkit#12]
I'm experimenting with both the request pointcloud data link and the request camera data link. On the camera data link I'm seeing rqt_topic report the relay topic `/usb_cam0/workstation/image/x264` using about 50K/s while the actual network throughput is over 600K/s. Turning off that subscription, the network idles at about 3K/s. When I subscribe directly to the `/usb_cam0/image_raw/x264` the network throughput is around 75K/s, which is what is should be.

In a somewhat opposite case, when I subscribe to the pointcloud relay, rqt_topic reports the bandwidth at around 1.2MB/s while the actual network traffic is only around 350K/s, which seems right based on what the request_pointcloud_link_startpoint reports it's compressing the messages to.

Any ideas on what could describe this?

Screenshot of camera bandwidth:
![datalink_network_usage](https://cloud.githubusercontent.com/assets/270854/14833856/132016b2-0bb6-11e6-8df8-32947c7049ed.png)

Screenshot of pointcloud bandwidth:
![datalink_network_usage2](https://cloud.githubusercontent.com/assets/270854/14833857/132257ce-0bb6-11e6-99e4-7d29fbc2d1eb.png)

```
	<node pkg="opportunistic_link" type="request_camera_link_startpoint" name="$(arg node_name)_link_startpoint" output="$(arg output)" >
		<!-- Request node params -->
		<param name="data_service" type="string" value="$(arg image_name)/data" />
		
		<!-- Limited node params -->
		<param name="link_topic" type="string" value="$(arg image_name)/data_link" />
		<param name="link_ctrl" type="string" value="$(arg image_name)/link_ctrl" />
		<param name="rate_ctrl" type="string" value="$(arg image_name)/rate_ctrl" />
		
		<!-- Request and Limited params -->
		<!-- <param name="camera_topic" type="string" value="$(arg image_name)/resized/image" /> -->
		<param name="camera_topic" type="string" value="$(arg image_name)/image_raw" />
		<remap from="/tf" to="$(arg remapped_tf)" />
	</node>

	<node pkg="opportunistic_link" type="request_camera_link_endpoint" name="$(arg node_name)_link_endpoint" output="$(arg output)" >
		<!-- Request node params -->
		<param name="override_timestamps" type="bool" value="$(arg override_timestamps)" />
		<param name="default_rate" type="double" value="$(arg default_rate)" />
		<param name="default_quality" type="int" value="$(arg quality)" />
		<param name="quality_ctrl" type="string" value="$(arg image_name)/quality" />
		<param name="rate_ctrl" type="string" value="$(arg image_name)/rate" />
		<param name="data_service" type="string" value="$(arg image_name)/data" />
		<param name="relay_topic" type="string" value="$(arg image_name)/workstation/image" />

		<!-- Limit node params -->
		<param name="relay_base_topic" type="string" value="$(arg image_name)/workstation/image" />
		<param name="link_image_topic" type="string" value="$(arg image_name)/data_link" />
		<param name="link_info_topic" type="string" value="$(arg image_name)/info_link" />
		<param name="link_ctrl" type="string" value="$(arg image_name)/link_ctrl" />

		<!-- Request and Limited params -->
		<param name="latched" type="bool" value="true" />
		<remap from="/tf" to="$(arg remapped_tf)" />
	</node>

	<node pkg="opportunistic_link" type="request_pointcloud_link_startpoint" name="$(arg node_name)_link_startpoint" output="$(arg output)">
		<param name="pointcloud_topic"   type="string"   value="$(arg pointcloud_name)" />
		<param name="compression_type"   type="string"   value="$(arg compression_type)" />
		<param name="data_service"       type="string"   value="$(arg pointcloud_name)/data" />
		<param name="link_topic"         type="string"   value="$(arg pointcloud_name)/compressed" />
	</node>

	<node pkg="opportunistic_link" type="request_pointcloud_link_endpoint" name="$(arg node_name)_link_endpoint" output="screen" >
		<param name="relay_topic"          type="string"   value="$(arg pointcloud_name)/workstation" />
		<param name="data_service"         type="string"   value="$(arg pointcloud_name)/data" />
		<param name="rate_ctrl"            type="string"   value="$(arg pointcloud_name)/rate" />
		<param name="link_topic"           type="string"   value="$(arg pointcloud_name)/compressed" />
		<param name="filter_ctrl"          type="string"   value="$(arg pointcloud_name)/quality" />
		<param name="latched"              type="bool"     value="true" />
		<param name="default_rate"         type="double"   value="$(arg default_rate)" />
		<param name="default_filter_size"  type="double"   value="$(arg default_filter_size)" />
		<param name="override_timestamps"  type="bool"     value="false" />
		
		<remap from="/tf" to="$(arg remapped_tf)" />
	</node>
```

**Comment by calderpg** [comment]
If I understand correctly what you're doing, you have an x264-encoded ImageTransport publisher that you're trying to relay. What you are seeing is what I'd expect to see - the ImageTransport publisher is using a more efficient encoding of full/partial frames, while the relay is using full JPEG-encoded full frames. At reasonable frame rates and high JPEG quality, I would expect the x264 stream to use significantly less data.

This is a consequence of design decisions we made when we developed the toolkit and limitations of ImageTransport - we assumed that lower frame rates would be used (so no having partial frames wouldn't add too much overhead), and that missed/delayed messages shouldn't break the relay (ImageTransport doesn't handle multiple subscribers or dropped frames well), so we used JPEG encoding of complete frames.

So long as your link is reliable, using an x264-encoded stream via ImageTransport is going to offer lower bandwidth use. If your link is unreliable, and/or you don't want to transmit every frame, you will get more reliable results using the relay with appropriately chosen resolution and JPEG quality.

One of the future improvements to the relay would be to swap in different encoders and the ability to use full/partial frames.

**Comment by zacwitte** [comment]
Gotcha - thanks for that context. I do like the features of the toolkit for
client side rate limiting and handling dark spots where the connection
drops out, etc. But that does seem to conflict with H264's incremental
changes between frames. I'll try working with direct H264 image_transport
for now. Hopefully that works smoothly enough for us.
