### ISSUE TITLE
opportunistic startpoints consuming 100% cpu

### ISSUE THREAD

**Issue by awesomebytes** [WPI-ARC/datalink_toolkit#8]
Hello, I would like to point out that, for example,

https://github.com/WPI-ARC/datalink_toolkit/blob/master/opportunistic_link/src/request_image_link_startpoint.cpp#L29-L35

The looping is done without any rate on it. This causes 100% CPU usage for every datalink.

I've added:

    while (ros::ok())
        {
            ros::spinOnce();
            ros::Duration(0.001).sleep(); // 1000Hz
        }
The sleep line, checking at 1000Hz sounds good enough as a default value. This makes the nodes consume 2% CPU.

I've seen you have this so-called "limited" nodes that do something like this but with the ability of changing this kind of rate but there is a lot more of logic. And I haven't seen any example launch file nor documentation (sorry if it's there and I didn't see it!).

Let me know if you think this modification makes sense to make a pull request. I'm gonna use it locally.

**Comment by calderpg** [comment]
You're correct that the link pairs use far more CPU than they should. What I'll do is add a brief sleep to each loop, but make it a parameter so people can change it to match their needs. I'll have to wait until I'm back from ICRA to test it fully, but the changes should be available by the middle of next week.

As for documentation on the "limited" variant nodes, I did make some documentation on them in an older version of the wiki. I'm going to go back and redo the documentation to be more complete, but in the mean time you can check the wiki page history and it should be there from a couple years ago.

**Comment by calderpg** [comment]
I've added a brief sleep to the loops of all the nodes. It defaults to 128Hz, but can be changed as a parameter. I'm going to close this issue, and make a new one for the improved documentation.

**Comment by awesomebytes** [comment]
Thanks! :)
